logos:
  - alt: Моя территория
    src: /static/img/logos/mt.png
  - alt: Контора пароходства
    src: /static/img/kp-logo-1-black.png
  - alt: Космос
    src: /static/img/logos/cosmos.png
  - alt: Медиацентр
    src: /static/img/logos/mediacenter.jpg
  - alt: Студенческий совет Тюменской области
    src: /static/img/logos/studsovet.jpg
  - alt: Медиаполис
    src: /static/img/03_cher.png
formBg: /static/img/form.jpg
title: Вездеход — 2021
heroSrc: /static/img/hero.jpg
og: /static/favicon/og.jpg
description:
  - text: Вездеход помогает вспомнить самые яркие и значимые моменты участия
      и организации проектов «Лига старост», «Тюменский кампус», «Медиасеть»,
      а также других проектов молодежных команд Тюменской области.
quotes:
  - quote: «Вездеход» — это возможность собрать в одно сообщество людей, которые
      делали и продолжают делать проекты, развивающие наше общество. За каждым
      из них стоит своя история, полная ценностей, трудностей и прорывов.
      Но самое главное, что каждый из них способен менять жизнь общества,
      формировать здоровую среду в городе и области.
    authorSrc: static/img/quotes/belyavskiy.jpg
    author: Павел Викторович Белявский
    authorJob: Директор департамента по общественным связям, коммуникациям
      и молодёжной политике Тюменской области
  - quote: Помню, что задумывался проект «Вездеход» как VIP-пропуск на все самые
      модные молодежные тусовки города. Сегодня «Вездеход» — это визитная
      карточка успешных, уверенных в своих силах единомышленников, воплощающих
      свои жизненные проекты в различных направлениях на территории нашего
      региона.
    authorSrc: static/img/quotes/salmin.jpg
    author: Алексей Павлович Салмин
    authorJob: Президент группы компаний «Автоград», депутат Тюменской областной
      Думы шестого созыва
hashtag: "#вездеход72"
formTitle: Отправь свою историю через форму на сайте
formText: и стань примером для молодежи Тюменской области!
formImgs:
  - alt: Артем Андросов
    src: /static/img/form/quote1.jpg
  - alt: Максим Бойко
    src: /static/img/form/quote2.jpg
  - alt: Маргарита Посадских
    src: /static/img/form/quote3.jpg
  - alt: Александра Раздорских
    src: /static/img/form/quote4.jpg
  - alt: Илья Титов
    src: /static/img/form/quote5.jpg
  - alt: Федор Маслов
    src: /static/img/form/quote6.jpg
email: karacheviv1995@gmail.com
