title: Вездеход — 2021
description:
  - text: Проект, который объединяет участников молодежных проектов, руководителей
      и сотрудников молодежных департаментов, команд и сообществ прошлых лет.
  - text: Вездеход помогает вспомнить самые яркие и значимые моменты участия
      и организации проектов.
quote: Вездеход — это возможность собрать в одно сообщество людей, которые создавали и развивали молодежную политику в Тюменской области. За каждым выпускником стоит своя история, полная ценностей, трудностей и прорывов. Но самое главное, что каждый из них способен менять жизнь общества, формировать здоровую среду в городе и области
author: Павел Викторович Белявский
authorJob: Директор департамента общественных связей ТО
hashtag: "#вездеход72"
