title: Вездеход — 2021
heroSrc: /static/img/hero.jpg
og: /static/favicon/og.jpg
logos:
  - alt: Моя территория
    src: /static/img/logos/mt.png
  - alt: Контора пароходства
    src: /static/img/logos/kontora.jpg
  - alt: Космос
    src: /static/img/logos/cosmos.png
  - alt: Медиацентр
    src: /static/img/logos/mediacenter.jpg
  - alt: Студенческий совет Тюменской области
    src: /static/img/logos/studsovet.jpg
  - alt: Медиаполис
    src: /static/img/logos/mediapolis.png
description:
  - text: Проект, который объединяет участников молодежных проектов, лидеров сообществ, а также руководителей и сотрудников молодежных команд прошлых лет.
  - text: "Вездеход помогает вспомнить самые яркие и значимые моменты участия и организации проектов «Лига старост», «Тюменский кампус», «Медиасеть», а также других проектов молодежных команд Тюменской области."
quotes:
  - quote: «Вездеход» — это возможность собрать в одно сообщество людей, которые делали и продолжают делать проекты, развивающие наше общество. За каждым из них стоит своя история, полная ценностей, трудностей и прорывов. Но самое главное, что каждый из них способен менять жизнь общества, формировать здоровую среду в городе и области.
    authorSrc: static/img/quotes/belyavskiy.jpg
    author: Павел Викторович Белявский
    authorJob: Директор департамента по общественным связям, коммуникациям и молодёжной политике Тюменской области
  - quote: Помню, что задумывался проект «Вездеход» как VIP-пропуск на все самые модные молодежные тусовки города. Сегодня «Вездеход» — это визитная карточка успешных, уверенных в своих силах единомышленников, воплощающих свои жизненные проекты в различных направлениях на территории нашего региона.
    authorSrc: static/img/quotes/salmin.jpg
    author: Алексей Павлович Салмин
    authorJob: Президент группы компаний «Автоград», депутат Тюменской областной Думы шестого созыва
hashtag: "#вездеход72"
formText: Приходи в Мою Территорию и получи приглашение на закрытую вечеринку.
formBg: /static/img/form.jpg
email: karacheviv1995@gmail.com