title: Вездеход — 2021
description:
  - text: Проект, который объединяет участников молодежных проектов, руководителей
      и сотрудников молодежных департаментов, команд и сообществ прошлых лет.
  - text: "Вездеход помогает вспомнить самые яркие и значимые моменты участия и организации проектов «Лига старост», «Тюменский кампус», «Медиасеть», а также других проектов молодежных команд Тюменской области."
quotes:
  - quote: «Вездеход» — это возможность собрать в одно сообщество людей, которые создавали и развивали молодежную политику в Тюменской области. За каждым из них стоит своя история, полная ценностей, трудностей и прорывов. Но самое главное, что каждый из них способен менять жизнь общества, формировать здоровую среду в городе и области.
    author: Павел Викторович Белявский
    authorJob: Директор департамента общественных связей ТО
  - quote: «Вездеход» — это возможность собрать в одно сообщество людей, которые создавали и развивали молодежную политику в Тюменской области. За каждым из них стоит своя история, полная ценностей, трудностей и прорывов. Но самое главное, что каждый из них способен менять жизнь общества, формировать здоровую среду в городе и области.
    author: Алексей Павлович Салмин
    authorJob: Президент группы компаний «Автоград», депутат Тюменской областной Думы шестого созыва
hashtag: "#вездеход72"
