backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"
site_url: https://вездеход72.рф
locale: 'ru'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Вездеход"
    name: "stories"
    editor:
      preview: false
    files:
      - label: "Содержимое страницы"
        name: "settings"
        file: "src/_data/stories/settings.yaml"
        fields:
          - { label: "Заголовок страницы", name: title, widget: string }
          - { label: "Заглавная картинка", name: heroSrc, widget: image, allow_multiple: false, hint: "1290х725 пикселей", required: false }
          - { label: "Картинка для упоминаний в соцсетях", name: og, widget: image, allow_multiple: false, hint: "1280×640 пикселей", required: false }
          - label: "Описание проекта"
            label_singular: "абзац"
            name: description
            widget: list
            fields:
              - { label: "Абзац текста", name: text, widget: text }
          - label: "Логотипы других проектов"
            label_singular: "логотип"
            name: logos
            widget: list
            fields:
              - { label: "Название", name: alt, widget: string }
              - { label: "Логотип проекта", name: src, widget: image, allow_multiple: false }
          - label: "Цитаты"
            label_singular: "цитата"
            name: quotes
            widget: list
            fields:
              - { label: "Автор цитаты", name: author, widget: string, required: false }
              - { label: "Должность автора", name: authorJob, widget: string, required: false }
              - { label: "Фотография автора", name: authorSrc, widget: image, allow_multiple: false, hint: "170х170 пикселей", required: false }
              - { label: "Цитата", name: quote, widget: text, hint: "Без кавычек.", required: false }
          - { label: "Хештег проекта", name: hashtag, widget: string }
          - { label: "Заголовок формы с историей", name: formTitle, widget: string, required: false }
          - { label: "Текст рядом с формой истории", name: formText, widget: text, required: false }
          - { label: "Картинка рядом с формой истории", name: formBg, widget: image, allow_multiple: false, required: false }
          - { label: "Электронная почта для заявок с формы", name: email, widget: string }
      - label: "Направления историй"
        name: "themes"
        file: "src/_data/stories/themes.yaml"
        fields:
          - { label: "Заголовок раздела", name: title, widget: string }
          - label: "Список карточек"
            label_singular: "карточка"
            name: cards
            widget: list
            fields:
              - { label: "Заголовок", name: title, widget: string }
              - { label: "Описание", name: description, widget: string }
              - { label: "Иконка", name: src, widget: image, allow_multiple: false, hint: "600х600 пикселей", required: false }
      - label: "Команда проекта"
        name: "items"
        file: "src/_data/stories/team.yaml"
        fields:
          - label: "Команда проекта"
            label_singular: "человек"
            name: items
            widget: list
            fields:
              - { label: "Имя", name: name, widget: string }
              - { label: "Должность", name: job, widget: string }
              - { label: "Фотография", name: src, widget: image, allow_multiple: false, hint: "600х600 пикселей", required: false }
              - { label: "Ссылка на ВКонтакте", name: vk, widget: string, required: false }
              - { label: "Ссылка на Инстаграм", name: ig, widget: string, required: false }
              - { label: "Электронная почта", name: email, widget: string, required: false }
      - label: "Политика конфиденциальности"
        name: "policy"
        file: "src/_data/policy.yaml"
        fields:
          - { label: "Политика конфиденциальности", name: body, widget: markdown, editor_components: [] }
